# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kasa < Formula
  desc "CLI for esa."
  homepage "https://github.com/winebarrel/kasa"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/kasa/releases/download/v0.6.2/kasa_0.6.2_darwin_amd64.tar.gz"
      sha256 "6991cd61f95c471aa68e1373b7e7f3d2e67e0ce1d7bed28df2d80379a9ce183d"

      def install
        bin.install 'kasa'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/kasa/releases/download/v0.6.2/kasa_0.6.2_darwin_arm64.tar.gz"
      sha256 "1f4aa3e00c7294af09b502a2f8d9bf5b45b5b0e39b32d81deafdd9798038e2c6"

      def install
        bin.install 'kasa'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/kasa/releases/download/v0.6.2/kasa_0.6.2_linux_arm64.tar.gz"
      sha256 "c58a4aa129e1549923758a6c354d9f087dbbd33840cb3207f2b796ee3944a4b2"

      def install
        bin.install 'kasa'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/kasa/releases/download/v0.6.2/kasa_0.6.2_linux_amd64.tar.gz"
      sha256 "ca7658aea7fff8620f1236df3bcdf9d97230ba3f100e3303ee5b4c7ebbf070f7"

      def install
        bin.install 'kasa'
      end
    end
  end
end
